package SweetCupcake_Management_System;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shena
 */
public class ManagerFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManagerFrame
     */
    public ManagerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jcupcakeid = new javax.swing.JTextField();
        jcupcakename = new javax.swing.JTextField();
        jcategory = new javax.swing.JComboBox();
        jprice = new javax.swing.JTextField();
        jquantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jcncashier = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setPreferredSize(new java.awt.Dimension(846, 574));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("WELCOME!");
        jPanel7.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 17, -1, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("The Sweet Cupcake Shop - Manager Dashboard");
        jPanel7.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 53, -1, -1));

        jLabel51.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Add New Cupcake");
        jPanel7.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 115, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Cupcake ID");
        jPanel7.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 164, -1, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Cupcake Name");
        jPanel7.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 209, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Category");
        jPanel7.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 258, -1, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Price");
        jPanel7.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 309, -1, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Quantity");
        jPanel7.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 359, -1, -1));

        jcupcakeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcupcakeidActionPerformed(evt);
            }
        });
        jPanel7.add(jcupcakeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 158, 147, 31));

        jcupcakename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcupcakenameActionPerformed(evt);
            }
        });
        jPanel7.add(jcupcakename, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 202, 147, 33));

        jcategory.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jcategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Classic Flavors", "Seasonal Specials", "Custom Orders", "Gluten-Free", "Beverages", "Dessert Combos" }));
        jPanel7.add(jcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 253, 146, 31));

        jprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpriceActionPerformed(evt);
            }
        });
        jPanel7.add(jprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 302, 147, 33));

        jquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jquantityActionPerformed(evt);
            }
        });
        jPanel7.add(jquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 352, 147, 32));

        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 402, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Classic Flavors", "Seasonal Specials", "Custom Orders", "Gluten-Free", "Beverages", "Dessert Combos" }));
        jPanel7.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 447, 119, 32));

        jButton2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 445, 114, 36));

        jButton3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton3.setText("View all Cupcakes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 499, 154, 39));

        jButton4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 499, 90, 39));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 476, 415));

        jcncashier.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jcncashier.setText("Create New Cashier");
        jcncashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcncashierActionPerformed(evt);
            }
        });
        jPanel7.add(jcncashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 565, 279, 41));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SweetCupcake_Management_System/dash.jpeg"))); // NOI18N
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcupcakenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcupcakenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcupcakenameActionPerformed

    private void jquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jquantityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           // Get input values
        String id = jcupcakeid.getText();
        String name = jcupcakename.getText();
        String category = jcategory.getSelectedItem().toString();
        String price = jprice.getText();
        String quantity = jquantity.getText();

        // Validation
        if (id.equals("") || name.equals("") || price.equals("") || quantity.equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter All Data");
            return;
        }
        // Create a supply object
        Cupcake cupcake = new Cupcake(id, name, category, price, quantity);

        // Initialize FileManager and SupplyManager
        FileManager fileManager = new FileManager("Cupcake.txt");
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        CupcakeManager cupcakeManager = new CupcakeManager(fileManager, tableModel);

        // Add supply to the system
        cupcakeManager.addCupcake(cupcake);

        // Clear input fields
        jcupcakeid.setText("");
        jcupcakename.setText("");
        jcategory.setSelectedIndex(0);
        jprice.setText("");
        jquantity.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     String selectedCategory = (String) jComboBox2.getSelectedItem();
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);

       try (BufferedReader br = new BufferedReader(new FileReader("Cupcake.txt"))) {
           String line;
           while ((line = br.readLine()) != null) {
             // Skip empty lines
             if (line.trim().isEmpty()) {
               continue;
             }

             // Split the line and check if it has the expected number of fields
             String[] fields = line.split(",");
             if (fields.length < 5) {
               // Skip or log the improperly formatted line
               System.err.println("Skipping malformed line: " + line);
               continue;
             }

               String id = fields[0];
               String name = fields[1];
               String category = fields[2];
               String price = fields[3];
               String quantity = fields[4];

               if (category.equalsIgnoreCase(selectedCategory)) {
               model.addRow(new Object[]{id, name, category, price, quantity});
              }
          }
               } catch (IOException ex) {
                  JOptionPane.showMessageDialog(this, "Error reading file: " + ex.getMessage());
         }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
        tbModel.setRowCount(0);

        try{
            BufferedReader reader = new BufferedReader(new FileReader("Cupcake.txt"));
            String line;

            while ((line = reader.readLine()) != null) {
                String[] data = line.split(",");
                tbModel.addRow(data);
            }

            reader.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error loading data from file.");
        }       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jcncashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcncashierActionPerformed
     jcncashier.addActionListener(new ActionListener() {
         @Override
         public void actionPerformed(ActionEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
         }
     });
    {
        newCashierFrame newCashierFrame = new newCashierFrame();
        newCashierFrame.setVisible(true);
        
        dispose();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jcncashierActionPerformed

    private void jcupcakeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcupcakeidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcupcakeidActionPerformed

    private void jpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jcategory;
    private javax.swing.JButton jcncashier;
    private javax.swing.JTextField jcupcakeid;
    private javax.swing.JTextField jcupcakename;
    private javax.swing.JTextField jprice;
    private javax.swing.JTextField jquantity;
    // End of variables declaration//GEN-END:variables
}

  class BuffereReader {

        public BuffereReader() {
        }
    }

    class JOptionsPane {

        private static void showMessageDialog(Managerframe aThis, String string) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public JOptionsPane() {
        }
    }

